module.exports = [
  [
      'GET',
      '/data',
      '../controllers/data',
      'getIndex'
  ],
  [
    'POST',
    '/getDataSummary',
    '../controllers/data',
    'getDataSummary'
  ],
  [
    'POST',
    '/getDataGoodsSummary',
    '../controllers/data',
    'getDataGoodsSummary'
  ],
  [
    'POST',
    '/getDataTradeSummary',
    '../controllers/data',
    'getDataTradeSummary'
  ],
];