module.exports = [
  [
      'GET',
      '/goodsH5',
      '../controllers/goodsH5',
      'getIndex'
  ],
  [
    'POST',
    '/loginH5',
    '../controllers/goodsH5',
    'postLoginH5'
  ],
  [
    'POST',
    '/pushOrder',
    '../controllers/goodsH5',
    'postPushOrder'
  ],
  [
    'POST',
    '/pushComment',
    '../controllers/goodsH5',
    'postPushComment'
  ],
];